# Generated by Django 4.2.7 on 2024-02-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_notes_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_dark',
            field=models.BooleanField(default=False),
        ),
    ]
