# Generated by Django 4.2.7 on 2024-02-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_teacher_is_dark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('grade', models.IntegerField(max_length=50, null=True)),
                ('assignments', models.ManyToManyField(related_name='assignments', to='base.assignment')),
            ],
        ),
    ]
